SELECT 'aBCDEF' ,
       INITCAP('aBCDEF')
FROM DUAL;

SELECT ENAME, LOWER(ENAME), LENGTH(ENAME)
FROM EMP;

SELECT LENGTHB('안녕하세요')
FROM DUAL;

SELECT CONCAT('abc','def') FROM DUAL;

SELECT LENGTHB('ABCD') FROM DUAL;

SELECT LENGTH('안녕하세요'), LENGTHB('안녕하세요') FROM DUAL;

SELECT SUBSTR('ABCD',2) FROM DUAL;

SELECT LPAD('가나다',8,'가') FROM DUAL;

SELECT SUBSTR('ABD',3) FROM DUAL;

SELECT LTRIM('가나다', '가') FROM DUAL;

SELECT RTRIM('가나다', '다') FROM DUAL;

SELECT SYSDATE FROM DUAL;

SELECT EXTRACT(MONTH FROM SYSDATE ) FROM DUAL;

SELECT SYSDATE + 10 FROM DUAL;

SELECT HIREDATE, HIREDATE+1000 FROM EMP;

SELECT (TO_DATE('2020-01-01 12:32오후','YYYY-MM-DD HH:MI PM')-HIREDATE) FROM EMP;

SELECT (TO_CHAR(SYSDATE,'YYYY-MM-DD HH:MI PM')) FROM DUAL;

SELECT TO_CHAR(HIREDATE,'MM/DD/YY')  FROM EMP;

SELECT ENAME,
       CASE WHEN ENAME LIKE'S%' THEN'S'
            WHEN ENAME LIKE'A%' THEN'A'
       ELSE 'X' END AS 출력
FROM EMP;

SELECT DEPTNO, DECODE(DEPTNO, 10,'TRUE')
FROM EMP;

SELECT EMPNO,ENAME,DEPTNO
FROM EMP
WHERE 1=NULL;

SELECT EMPNO,ENAME,SAL FROM EMP ORDER BY EMPNO DESC;

SELECT JOB,SUM(SAL) FROM EMP GROUP BY JOB ;

SELECT AVG(SAL),SUM(SAL) FROM EMP;

--------------------------------------------------------------------------------

SELECT DEPTNO,MGR,SUM(SAL)
FROM EMP
GROUP BY GROUPING SETS(DEPTNO, MGR,())
ORDER BY DEPTNO;

SELECT JOB 직무, SUM(SAL), COUNT(*) 인원
FROM EMP
GROUP BY ROLLUP(JOB);

SELECT MGR,DEPTNO,SUM(SAL)
FROM EMP
GROUP BY ROLLUP(MGR, DEPTNO);

